name: gamesmith
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - openai==1.78.1
    - python-dotenv
    - pydantic==2.11.4
    - requests>=2.0.0
    - replicate
    - pillow==11.2.1